# recover-test

It is sometimes very important to interrupt the program without exiting it. One possibility is to panic and catch it with recover. I have recorded how this works in this small example.
